<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Assignment Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            line-height: 1.4;
            font-size: 14px;
        }
        .header {
            border-bottom: 2px solid #059669;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        .school-name {
            font-size: 24px;
            font-weight: bold;
            color: #0f172a;
        }
        .report-title {
            font-size: 16px;
            color: #4b5563;
            margin-top: 5px;
        }
        .meta-grid {
            margin-bottom: 30px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            border-radius: 8px;
        }
        .meta-item {
            margin-bottom: 8px;
        }
        .meta-label {
            font-weight: bold;
            color: #475569;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f1f5f9;
            color: #475569;
            font-weight: bold;
            text-align: left;
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 12px;
            text-transform: uppercase;
        }
        td {
            padding: 12px 10px;
            border-bottom: 1px solid #f1f5f9;
        }
        .rank {
            font-weight: bold;
            color: #64748b;
        }
        .score {
            font-weight: bold;
            color: #059669;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
            border-top: 1px solid #f1f5f9;
            padding-top: 15px;
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="school-name">{{ $school->name }}</div>
        <div class="report-title">Assignment Performance Report</div>
    </div>

    <div class="meta-grid">
        <div class="meta-item"><span class="meta-label">Assignment:</span> {{ $assignment->title }}</div>
        <div class="meta-item"><span class="meta-label">Exam / Subject:</span> {{ $assignment->exam?->name }} / {{ $assignment->subject?->name ?: 'All' }}</div>
        <div class="meta-item"><span class="meta-label">Questions:</span> {{ $assignment->question_count }} questions</div>
        <div class="meta-item"><span class="meta-label">Generated:</span> {{ now()->format('F d, Y H:i WAT') }}</div>
    </div>

    <h3>Student Leaderboard / Results</h3>

    <table>
        <thead>
            <tr>
                <th style="width: 10%;">Rank</th>
                <th style="width: 45%;">Student Name / Email</th>
                <th style="width: 25%;">Score</th>
                <th style="width: 20%;">Time Taken</th>
            </tr>
        </thead>
        <tbody>
            @forelse($results as $index => $res)
                <tr>
                    <td class="rank">#{{ $index + 1 }}</td>
                    <td>
                        <div style="font-weight: bold; color: #0f172a;">{{ $res->user->name }}</div>
                        <div style="font-size: 11px; color: #64748b;">{{ $res->user->email }}</div>
                    </td>
                    <td class="score">{{ $res->score }}% ({{ $res->correct_count }}/{{ $res->total_questions }})</td>
                    <td>{{ $res->time_taken_secs ? gmdate('i:s', $res->time_taken_secs) . ' mins' : '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; color: #94a3b8; padding: 20px;">
                        No submissions recorded for this assignment yet.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by CBTWise School Partner Portal • © {{ date('Y') }} CBTWise. All rights reserved.
    </div>

</body>
</html>
